apiVersion: v1
kind: Service
metadata:
  name: details-nodejs
  labels:
    app: details
    service: details
    name: app-metrics-label
spec:
  selector:
    app: details-nodejs
  ports:
    - port: 9080
      targetPort: 3000
      name: http
