apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: productpage
    version: v2
  name: productpage-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: productpage
        version: v2
    spec:
      containers:
        - image: de.icr.io/kmddk/bookinfo-productpage-mn:e37d111
          imagePullPolicy: Always
          name: productpage
          ports:
            - containerPort: 9080
              protocol: TCP
